name: Deploy Django Application

on:
  push:
    branches:
      - master  # O la rama que utilices para el despliegue

jobs:
  deploy:
    runs-on: windows-latest  # Usamos Windows para que sea compatible con tu entorno de XAMPP

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'  # O la versión que estés utilizando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd mierpti1a
          pip install -r requirements.txt

      - name: Run Django migrations
        run: |
          python manage.py migrate

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy to Apache (Windows-specific)
        run: |
          # Aquí puedes agregar comandos para copiar los archivos de tu repositorio
          # al servidor local donde XAMPP esté corriendo, por ejemplo, usando robocopy:
          robocopy /E /Z /COPYALL /R:3 /W:5 $(System.DefaultWorkingDirectory) "C:/Users/simi2/Downloads/DjangoProtect/TiendaEnLinea/mierpti1a"
